# Anna R. Rogers
# CS 590 Fall 2019
# <font color='red'>Week 3 - Introduction to NumPy Exercise</font>

This week focused on NumPy, a module or library in Python that processes arrays and matrices for mathematical compuatation. This exercise is designed to review the materials covered in the lecture

#### Import Shorthanded NumPy (Hint: np)

In [6]:
import numpy as np

#### Create an array of 10 zeros

In [14]:
array = np.zeros([1, 10])
array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create and array of 10 ones

In [15]:
array = np.ones([1, 10])
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [16]:
array = np.ones([1, 10]) * 5 #Just multiply the ones array by 5 to get an array of fives
array

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of integers from 10 to 50

In [23]:
array = np.arange(10, 51, 1)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [24]:
array = np.arange(10, 51, 2)
array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3 x 3 matrix (array) with values ranging from 0 to 8

In [26]:
matrix_3 = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
np.array(matrix_3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1, 2],
       <br>[3, 4, 5],
       <br>[6, 7, 8]])

#### Create a 3 x 3 matrix (matrix) with values ranging from 0 to 8

In [27]:
matrix_3 = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
np.matrix(matrix_3) #Use NumPy matrix to make the matrix a matrix

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

matrix([[0, 1, 2],
        <br>[3, 4, 5],
        <br>[6, 7, 8]])

#### Create a 3 x 3 identity matrix

In [28]:
np.eye(3) #Identity matrix using NumPy

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       <br>[0., 1., 0.],
       <br>[0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [30]:
np.random.rand(1) #use random to generate a random number

array([0.81876901])

array([0.89708448])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [31]:
np.random.randn(25) #Change to randn to get normal distribution

array([ 0.50078315, -0.38371217, -1.28462714, -0.40751997, -1.10724085,
        0.48548407, -0.88492321,  1.46190381, -1.3881334 ,  0.27884964,
       -1.30344849, -1.27062135, -0.19659293, -0.33919897, -0.49086334,
        0.49821904, -0.06440018,  0.18525714,  0.7278441 , -2.53422265,
       -1.85858417,  0.70742393, -1.0241985 ,  0.65902309, -0.57586619])

np.random.randn(25)

#### Create the following matrix:
array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       <br>[0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       <br>[0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       <br>[0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       <br>[0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       <br>[0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       <br>[0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       <br>[0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       <br>[0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       <br>[0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [32]:
#Numbers are from 0.01 to 1 increment by 0.01.  Use np linspace
np.linspace(0.01, 1, 100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### Create an array of 20 linearly spaced points between 0 and 1

In [33]:
np.linspace(0, 1, 20) #From 0 to 1, 20 even points

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

np.linspace(0,1,20)

## NumPy Indexing and Selection

Use the provided matrix (array) to replicate the resulting matrix (array) output

In [34]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[ 1,  2,  3,  4,  5],
       <br>[ 6,  7,  8,  9, 10],
       <br>[11, 12, 13, 14, 15],
       <br>[16, 17, 18, 19, 20],
       <br>[21, 22, 23, 24, 25]])

In [38]:
mat[2:5, 1:5] #Can either use this or mat[2:5, 1:]
mat[2:, 1:] #This also works here

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       <br>[17, 18, 19, 20],
       <br>[22, 23, 24, 25]])

In [39]:
mat[3,4] #In the orginal matrix, row 4 col 5 which indexes as 3, 4 due to starting at zero

20

20

In [40]:
mat[0:3, 1:2] #Grab the first 3 rows and the second column

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       <br>[ 7],
       <br>[12]])

In [42]:
mat[4:5,] #Grab the last row

array([[21, 22, 23, 24, 25]])

array([21, 22, 23, 24, 25])

In [43]:
mat[3:5, ]#Grab the last two rows

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       <br>[21, 22, 23, 24, 25]])

## Matrix Operations

Use the matrix > mat to detemine the following:

#### Calculate the sum of all the values in mat

In [45]:
np.sum(mat)

325

325

#### Calculate the standard deviation of the values in mat

In [46]:
np.std(mat)

7.211102550927978

7.211102550927978

#### Calculate the sum of all the columns in mat

(Hint: Look up in the **sum()** method, refer to the axis of the matrix [0, 1])

In [47]:
sum(mat)

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])